### ISSUE TITLE
Doesn't seem to work on MacOS Sierra

### ISSUE THREAD

**Issue by gdiggs** [avsm/docker-ssh-agent-forward#6]
Ever since upgrading to Sierra, this doesn't work for me anymore. Anyone else seeing this / have a workaround?

**Comment by BlinkyStitt** [comment]
It think it used to work for me on Sierra, but now it isn't working anymore. I'm on Sierra 10.12.2 and Docker Version 1.13.0-beta38 (15084). I'm going to try to go through backups and see what version of Docker last worked

```
$ docker --version
Docker version 1.13.0, build 49bf474
```

```
$ pinata-ssh-mount
cat: /Users/bwstitt/.pinata-sshd/agent_socket_path: No such file or directory
-v /Users/bwstitt/.pinata-sshd/:/tmp/ssh-agent.sock --env SSH_AUTH_SOCK=/tmp/ssh-agent.sock

$ ls ~/.pinata-sshd
known_hosts

```

**Comment by ABaldwinHunter** [comment]
@GordonDiggs what's the error you're seeing? I'm not sure if this is related, but I started seeing:

```
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/usr/bin/tini\": stat /usr/bin/tini: no such file or directory"
```

Also using docker 1.13.0, git commit 49bf474, but OS X Yosemite 10.10.5

**Comment by BlinkyStitt** [comment]
@ABaldwinHunter the tini error is fixed by https://github.com/avsm/docker-ssh-agent-forward/pull/7.

Unfortunately, that fix wasn't enough for me. Now the container just uses 200% CPU as soon as I try to ssh in.

**Comment by BlinkyStitt** [comment]
I fixed my local system!

Something was wrong inside Docker. I updated to the latest version (1.13.0) and then went into preferences and clicked the "Reset" bomb and then "Reset to factory defaults" and now its working again (well after I did a bunch of other cleanup things on https://github.com/uber-common/docker-ssh-agent-forward)

**Comment by ABaldwinHunter** [comment]
@WyseNynja thanks for the update! glad your system is working well. Going to try out the bug fix you mentioned and see how it goes

**Comment by chad-10e** [comment]
PR #15 includes the fix linked by @WyseNynja.

**Comment by jeffrey-aguilera** [comment]
Just reset docker to factory defaults (17.0.3.1-ce-mac5) and still have the same issue:
```
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/usr/bin/tini\": stat /usr/bin/tini: no such file or directory".
```

**Comment by micmart** [comment]
#15 fixed the error above. But now I get this error:
ssh_exchange_identification: Connection closed by remote host

**Comment by rawrgulmuffins** [comment]
Also hitting this unfortunately.

**Comment by BlinkyStitt** [comment]
@rawrgulmuffins Try my fork: https://github.com/uber-common/docker-ssh-agent-forward
